# Add application configuration variables here, as shown below.
#

SITE_NAME: My Digital Store

# Used by capistrano to deploy your application to the production server
DEPLOY_HOST: example.com 
DEPLOY_USER: deploy
# If you want to deploy to a staging server, set these:
#STAGING_HOST: staging.example.com
#STAGING_USER: deploy

# Payment through stripe
STRIPE_API_KEY: Your_Stripe_API_key
STRIPE_PUBLIC_KEY: Your_Stripe_Public_key

# Mandrill is for sending email:
MANDRILL_USERNAME: Your_Username
MANDRILL_APIKEY: Your_API_Key
DEFAULT_FROM: info@domain.com
HOST_FOR_MAILER: domain.com

# For support contact form. Leave blank to hide contact form
SUPPORT_EMAIL: support@domain.com
SUPPORT_PHONE: 

# Seeds the first user as an admin:
ADMIN_NAME: Admin User
ADMIN_EMAIL: admin@email.com
ADMIN_PASSWORD: secret

# Social login keys. If you don't want to use one of these providers,
# just leave the setting blank.
OMNIAUTH_TWITTER_KEY: Your_OmniAuth_Twitter_Key
OMNIAUTH_TWITTER_SECRET: Your_OmniAuth_Twitter_Secret

FACEBOOK_KEY: Your_Facebook_Key
FACEBOOK_SECRET: Your_Facebook_Secret

GPLUS_KEY: Your_Google_Plus_Key
GPLUS_SECRET: Your_Google_Plus_Secret

SOUNDCLOUD_CLIENT_ID: Your_Soundcloud_ID
SOUNDCLOUD_SECRET: Your_Soundcloud_Secret

# General app setup and other stuff:
SECRET_KEY_BASE: 343ecd35a7104ae94cc64e04080c9c20501ac05f8ce6afcb5b48d2ad1e224aa44d19efa84d61e040f1563e8a6f4cebb786e687ec2167688eced7507e7b46f268
ROLES: [admin, user]

FIRST_CATEGORY: Digital Downloads
GOOGLE_ANALYTICS_ACCOUNT: UA-YourGA-ID
